name: BuildInBoxReborn
version: '${project.version}'
main: com.kradre.buildinboxreborn.BuildInBoxReborn
api-version: '1.20'
depend: [WorldEdit]
commands:
  bibr:
    description: Copy region and put it into the chest
  bibr list:
    description: List all chests used in the system
  bibr clone:
    description: Give specific chest from the list