name: BuildInBoxReborn
version: '${project.version}'
main: com.kradre.buildinboxreborn.BuildInBoxReborn
api-version: '1.20'
depend: [WorldEdit]
commands:
  'bibr':
    description: Copy region and put it into the chest
    usage: "/bibr <name>"
    aliases: [buildinbox, box]
    permission: bibr.create
    permission-message: "No block holes for you, mister"
permissions:
  bibr.create:
    description: "Create black hole chest"
    default: op
