name: BuildInBoxReborn
version: '${project.version}'
main: com.kradre.buildinboxreborn.BuildInBoxReborn
api-version: '1.20'
depend: [WorldEdit]
commands:
  bibr:
    description: Copy region and put it into the chest